### ISSUE TITLE
Add europeana

### ISSUE THREAD

**Issue by jnehring** [freme-project/dataset-conversion-scripts#4]
Please add the conversion script for the europeana dataset to this repository together with a documentation on how to use the script.

**Comment by pheyvaer** [comment]
Which conversion script?

**Comment by jnehring** [comment]
I think that europeana dataset was converted by iMinds to LOD. Further I assume that this was done using a script. Am I right?

**Comment by pheyvaer** [comment]
We didn't convert them to LOD. They were already in RDF/XML, however, we converted them to turtle. Additionally, we had to harvest the data, which took us several weeks. We can add the scripts for that. However, I don't know how useful it is for people. I think it might be more beneficial to give them the dataset. Furthermore, we only limited ourselves to the 'history collection', because else it would take us months before we would have all the data.

**Comment by jnehring** [comment]
When we provide the dump only then people are not able to retrieve the latest data.

Is the script hard to use / does it need a lot of documentation?

**Comment by pheyvaer** [comment]
I'll check and try to put the different scripts together with the required documentation.

**Comment by jnehring** [comment]
Thank you

**Comment by pheyvaer** [comment]
Fixed by b380b04
